name: E2E tests
on:
  push:
    branches:
      - develop
      - dev-e2e

jobs:
  bash-example-ls:
    runs-on: ubuntu-latest
    steps:
      - name: List dir and path
        run: |
            echo "ls command"
            pwd && ls -la

