name: E2E tests
on:
  push:
    branches:
      - develop
      - dev-e2e

jobs:
  test-plugin:
    name: Run E2E Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      API_KEY: ${{secrets.E2E_API_KEY}}
      API_SECRET: ${{secrets.E2E_API_SECRET}}

    steps:
      - name: Create dirs.
        run: |
              mkdir -p kco
      - name: Setup KCO
        uses: actions/checkout@v2
        with:
          path: kco
      - name: Setup Yarn
        run: |
          cd ./kco/tests/e2e/
          yarn install
      # - name: Run Tests
      #   run: |
      #     cd ./kco/tests/e2e/
      #     yarn e2e:test

      - name: List dir and path
        run: |
          echo "ls command"
          ls -la /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/

      - name: Set env variable
        id: vars
        shell: bash
        run: |
          cd ./kco/tests/e2e/
          yarn e2e:fake-test > outputs/rest.txt | tr -d '\n' < outputs/rest.txt | sed 's/^.*{/{/' | sed 's/}.*/}/' > outputs/rest2.txt
                    echo "ls command"
          ls -la /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/
          echo ::set-output name=e2e_res::$(cat /outputs/rest2.txt)

      - name: Send custom data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            ${{ steps.vars.outputs.e2e_res_2 }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: End Tests
        run: |
          cd ./kco/tests/e2e/
          yarn docker:down


      # - name: Run Tests
      #   run: |
      #     cd ./kco/tests/e2e/
      #     yarn docker:down

      
      
      # yarn docker:up && yarn wp:install && yarn jettison