name: E2E tests
on:
  push:
    branches:
      - develop
      - dev-e2e

jobs:
  test-plugin:
    name: Run E2E Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      API_KEY: ${{secrets.E2E_API_KEY}}
      API_SECRET: ${{secrets.E2E_API_SECRET}}

    steps:
      - name: Create dirs.
        run: |
              mkdir -p kco
      - name: Setup KCO
        uses: actions/checkout@v2
        with:
          path: kco
      - name: Setup Yarn
        run: |
          cd ./kco/tests/e2e/
          yarn install
      - name: Run Tests
        run: |
          cd ./kco/tests/e2e/
          yarn e2e:test
      - name: List dir and path
        run: |
          echo "ls command"
          ls -la /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/

      - name: Set env variable
        id: vars
        shell: bash
        run: |

          echo ::set-output name=e2e_res_2::$(node /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/format-output.js)
          echo ::set-output name=e2e_res_php::$(php -version)
      - name: Send custom data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            { 
              "php_version": "${{ steps.vars.outputs.e2e_res_php }}",
              "wc_version": "${{ steps.vars.outputs.e2e_res_2 }}",
              "wp_version": "${{ steps.vars.outputs.e2e_res_2 }}",
              "plugin_name": "${{ steps.vars.outputs.e2e_res_2 }}",
              "plugin_version": "${{ steps.vars.outputs.e2e_res_2 }}",
              "branch_name": "krokedil-dev-test",
              "link_to_test": "http://teste2elink.e2e.com"

            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
