name: E2E tests
on:
  push:
    branches:
      - develop
      - dev-e2e

jobs:
  test-plugin:
    name: Run E2E Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      API_KEY: ${{secrets.E2E_API_KEY}}
      API_SECRET: ${{secrets.E2E_API_SECRET}}

    steps:
      - name: Create dirs.
        run: |
              mkdir -p kco
      - name: Setup KCO
        uses: actions/checkout@v2
        with:
          path: kco
      - name: Setup Yarn
        run: |
          cd ./kco/tests/e2e/
          yarn install
      - name: Run Tests
        run: |
          cd ./kco/tests/e2e/
          yarn e2e:test
      - name: List dir and path
        run: |
          echo "ls command"
          ls -la /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/

      - name: Set env variable
        shell: bash
        run: |
          value=`cat /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/output.txt`
          echo $value
          echo "-------------"
          echo `TESTE2E= $value`
          echo `TESTE2E= $value` >> $GITHUB_ENV

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "test1": ${{ env.TESTE2E }},
              "test2": "Filler data"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}