name: E2E tests
on:
  push:
    branches:
      - develop
      - dev-e2e

jobs:
  test-plugin:
    name: Run E2E Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      API_KEY: ${{secrets.E2E_API_KEY}}
      API_SECRET: ${{secrets.E2E_API_SECRET}}




    steps:
T

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "test1":  "Hello"
              "test2": "Greetings"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}