name: E2E tests
on:
  push:
    branches:
      - develop
      - dev-e2e

jobs:
  test-plugin:
    name: Run E2E Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      API_KEY: ${{secrets.E2E_API_KEY}}
      API_SECRET: ${{secrets.E2E_API_SECRET}}

    steps:
      - name: Create dirs.
        run: |
              mkdir -p kco
      - name: Setup KCO
        uses: actions/checkout@v2
        with:
          path: kco
      - name: Setup Yarn
        run: |
          cd ./kco/tests/e2e/
          yarn install

      # - name: Run Tests
      #   run: |
      #     cd ./kco/tests/e2e/
      #     yarn e2e:test

      - name: Close any open images
        run: |
          cd ./kco/tests/e2e/
          yarn docker:down

      - name: Run Tests
        run: |
          cd ./kco/tests/e2e/
          yarn docker:up && yarn wp:install && yarn jettison

      - name: Get branch name
        shell: bash
        run: |
          cd ./kco/tests/e2e/
          echo ::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})

      - name: List dir and path
        run: |
          cd ./kco/tests/e2e/
          ls -la /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/tests/

      # Environment variables
      # WP
      - name: Get unformatted WP version
        shell: bash
        run: |
          cd ./kco/tests/e2e/
          yarn wp:version-run  > /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wp-version-temp.txt

      - name: Format WP version
        shell: bash
        run: |
          cat /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wp-version-temp.txt 
          cd ./kco/tests/e2e/
          sed '3q;d' < /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wp-version-temp.txt  >> /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wp-version-temp-no-lines-clean.txt
      
      # WC
      - name: Get unformatted WC details
        id: wcvar
        shell: bash
        run: |
          cd ./kco/tests/e2e/
          yarn wc:version-run > /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wc-version-temp.txt
    
      - name: Get unformatted WC version
        shell: bash
        run: |
          cat /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wc-version-temp.txt
          cd ./kco/tests/e2e/
          sed '7q;d' < /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wc-version-temp.txt  >> /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wc-version-temp-no-lines.txt 

      - name: Format WC version
        shell: bash
        run: |
          cd ./kco/tests/e2e/
          sed 's/.*://' < /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wc-version-temp-no-lines.txt  >> /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wc-version-temp-no-lines-clean.txt 
      
      # Klarna
      - name: Get unformatted Klarna details
        shell: bash
        run: |
          cd ./kco/tests/e2e/
          yarn klarna:version-run > /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-klarna-version-temp.txt
    
      - name: Get unformatted Klarna version
        shell: bash
        run: |
          cat /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-klarna-version-temp.txt
          cd ./kco/tests/e2e/
          sed '7q;d' < /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-klarna-version-temp.txt  >> /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-klarna-version-temp-no-lines.txt 

      - name: Format Klarna version
        shell: bash
        run: |
          cd ./kco/tests/e2e/
          sed 's/.*://' < /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-klarna-version-temp-no-lines.txt  >> /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-klarna-version-temp-no-lines-clean.txt 

      # PHP
      - name: Get unformatted PHP details
        shell: bash
        run: |
          cd ./kco/tests/e2e/
          yarn wp:php-version-run > /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-php-version-temp.txt
    
      - name: Get unformatted PHP version
        shell: bash
        run: |
          cat /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-klarna-version-temp.txt
          cd ./kco/tests/e2e/
          sed '7q;d' < /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-php-version-temp.txt  >> /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-php-version-temp-no-lines.txt 

      - name: Format PHP version
        shell: bash
        run: |
          cd ./kco/tests/e2e/
          sed 's/.*://' < /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-php-version-temp-no-lines.txt  >> /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-php-version-temp-no-lines-clean.txt 


      # Process variables

      - name: Get child WP version
        id: childwpver
        shell: bash
        run: |
          cat /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wp-version-temp-no-lines-clean.txt
          cd ./kco/tests/e2e/
          echo ::set-output name=child_wp_ver::$(cat /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wp-version-temp-no-lines-clean.txt )

      - name: Get child WC version
        id: childwcver
        shell: bash
        run: |
          cd ./kco/tests/e2e/
          cat /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wc-version-temp-no-lines-clean.txt
          echo ::set-output name=child_wc_ver::$(cat /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-wc-version-temp-no-lines-clean.txt )

      - name: Get child Klarna version
        id: childklarnaver
        shell: bash
        run: |
          cd ./kco/tests/e2e/
          cat /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-klarna-version-temp-no-lines-clean.txt
          echo ::set-output name=child_klarna_ver::$(cat /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-klarna-version-temp-no-lines-clean.txt )

      - name: Get child PHP version
        id: childphpver
        shell: bash
        run: |
          cd ./kco/tests/e2e/
          cat /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-php-version-temp-no-lines-clean.txt
          echo ::set-output name=child_php_ver::$(cat /home/runner/work/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce/kco/tests/e2e/outputs/child-klarna-version-temp-no-lines-clean.txt )

      # Send data to Slack
      - name: Send custom data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
            "wc_version": "${{steps.childwcver.outputs.child_wc_ver}}",
            "plugin_name": "temp plugin name",
            "wp_version": "${{ steps.childwpver.outputs.child_wp_ver}}",
            "php_version": "${{ steps.childphpver.outputs.child_php_ver}}" ,
            "plugin_version": "${{ steps.bash.outputs.child_klarna_ver}}",
            "workflow_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "branch_name": "${{ steps.current_branch.outputs.branch }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: End Tests
        run: |
          cd ./kco/tests/e2e/
          yarn docker:down