name: E2E tests
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{secrets.E2E_API_KEY}}
      API_SECRET: ${{secrets.E2E_API_SECRET}}
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: krokedil
          repo: e2e-tests
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          workflow_file_name: e2e-tests.yml
          ref: master
